"""Capture the Phoenix UI showing CredPilot's own traces.

AC-09 asks for a cost/latency dashboard as a *Phoenix screenshot plus the
underlying data file*. `scripts/build_dashboard.py` produces the chart and
`reports/phoenix_spans.csv` the data; this produces the screenshot of Phoenix
itself, so the claim "these spans are in Phoenix" is something a reader can
look at rather than take on trust.

NFR-06 is why this is a committed script rather than a picture someone took:
every evidence artifact must be machine-generated by committed code, and a
screenshot is an evidence artifact like any other.

Prerequisites, in order::

    python -m phoenix.server.main serve          # in another terminal
    python scripts/export_traces.py --phoenix    # send spans to it
    python scripts/capture_phoenix_screenshot.py

Playwright is a **development** dependency and deliberately not in
``requirements.txt`` — nothing at runtime needs a browser. Install it only to
regenerate this image::

    pip install playwright && python -m playwright install chromium

The script exits non-zero with the reason rather than writing a placeholder if
Phoenix is not reachable, the project holds no spans, or Playwright is not
installed. An image that does not show real traces would be worse than no
image.
"""

from __future__ import annotations

import argparse
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DEFAULT_BASE = "http://localhost:6006"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "assets" / "phoenix-traces.png"
#: Wide enough that the latency columns are legible, tall enough for the
#: span table to show more than a handful of rows.
VIEWPORT = {"width": 1680, "height": 1150}


def _phoenix_is_up(base: str, timeout: float = 5.0) -> tuple[bool, str]:
    try:
        with urllib.request.urlopen(f"{base}/healthz", timeout=timeout) as response:
            return response.status == 200, f"HTTP {response.status}"
    except urllib.error.URLError as exc:
        return False, str(exc.reason)
    except Exception as exc:  # noqa: BLE001
        return False, f"{type(exc).__name__}: {exc}"


def _span_count(project: str) -> tuple[int, str]:
    """How many spans Phoenix actually holds, read through its own client."""
    try:
        import phoenix as px

        frame = px.Client().get_spans_dataframe(project_name=project)
        return len(frame), ""
    except Exception as exc:  # noqa: BLE001
        return -1, f"{type(exc).__name__}: {exc}"



def _project_id(base: str, name: str) -> "str | None":
    """Phoenix's own id for a project, read from its API.

    A base64 global id that changes with the database, so it is resolved
    rather than written down.
    """
    import json

    try:
        with urllib.request.urlopen(f"{base}/v1/projects", timeout=10) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except Exception:  # noqa: BLE001
        return None
    rows = payload.get("data", payload) if isinstance(payload, dict) else payload
    for row in rows or []:
        if isinstance(row, dict) and row.get("name") == name:
            return row.get("id")
    return None

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--base-url", default=DEFAULT_BASE)
    parser.add_argument("--project", default="credpilot")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--path", default=None,
                        help="page to capture, relative to the base url; the "
                             "default is the project's own span table, whose id "
                             "is resolved from Phoenix's API")
    parser.add_argument("--settle-ms", type=int, default=6000,
                        help="how long to let the UI finish loading before capturing")
    args = parser.parse_args(argv)

    from src.console import use_utf8_stdio

    use_utf8_stdio()

    up, detail = _phoenix_is_up(args.base_url)
    if not up:
        print(f"Phoenix is not reachable at {args.base_url} ({detail}).")
        print("Start it with:  python -m phoenix.server.main serve")
        return 1
    print(f"Phoenix        {args.base_url}  ({detail})")

    count, error = _span_count(args.project)
    if count == 0:
        print(f"Project {args.project!r} holds no spans. Send some first:")
        print("  python scripts/export_traces.py --phoenix")
        return 1
    if count < 0:
        print(f"Could not read the span count: {error}")
        print("Capturing anyway would risk an image of an empty project.")
        return 1
    print(f"Spans in {args.project:<6} {count}")

    try:
        from playwright.sync_api import sync_playwright
    except ModuleNotFoundError:
        print("Playwright is not installed. It is a development dependency:")
        print("  pip install playwright && python -m playwright install chromium")
        return 1

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    path = args.path
    if path is None:
        project_id = _project_id(args.base_url, args.project)
        if project_id is None:
            print(f"Could not resolve a project id for {args.project!r} from "
                  f"{args.base_url}/v1/projects. Pass --path explicitly.")
            return 1
        path = f"/projects/{project_id}/spans"
        print(f"Project id     {project_id}")
    url = f"{args.base_url.rstrip('/')}{path}"

    with sync_playwright() as play:
        browser = play.chromium.launch()
        try:
            page = browser.new_page(viewport=VIEWPORT, device_scale_factor=2)
            response = page.goto(url, wait_until="networkidle", timeout=60_000)
            status = response.status if response is not None else 0
            if status >= 400:
                print(f"{url} returned HTTP {status}.")
                print(_diagnose(status))
                return 1

            # Phoenix streams its span table in after the network settles.
            page.wait_for_timeout(args.settle_ms)

            # A 200 is not proof the UI rendered: a server-side template error
            # can come back as a 200 body that says "Internal Server Error",
            # and the first version of this script screenshotted exactly that
            # and reported success.
            body = (page.inner_text("body") or "").strip()
            if _looks_like_an_error_page(body):
                print(f"{url} returned HTTP {status} but rendered an error page:")
                print(f"  {body.splitlines()[0][:120] if body else '(empty body)'}")
                print(_diagnose(status))
                return 1
            if not _looks_like_the_phoenix_ui(body):
                print(f"{url} rendered something, but nothing that identifies the "
                      "Phoenix UI or the project. Not capturing it.")
                print(f"  first line: {body.splitlines()[0][:120] if body else '(empty body)'}")
                return 1

            page.screenshot(path=str(output))
        finally:
            browser.close()

    size_kb = output.stat().st_size / 1024
    print(f"Captured       {url}")
    print(f"Screenshot   → {output.relative_to(REPO_ROOT)}  ({size_kb:,.0f} KB)")
    return 0


#: Text that means the page is an error, whatever status carried it.
_ERROR_MARKERS = (
    "internal server error",
    "not found",
    "502 bad gateway",
    "service unavailable",
    "application startup failed",
)

#: Text that means the Phoenix UI actually mounted.
_UI_MARKERS = ("phoenix", "projects", "traces", "spans", "credpilot")


def _looks_like_an_error_page(body: str) -> bool:
    lowered = body.lower()
    # An error page is short and says so. The real UI mentions "not found"
    # nowhere near the top, so the length bound keeps this from firing on it.
    return len(body) < 400 and any(marker in lowered for marker in _ERROR_MARKERS)


def _looks_like_the_phoenix_ui(body: str) -> bool:
    lowered = body.lower()
    return any(marker in lowered for marker in _UI_MARKERS)


def _diagnose(status: int) -> str:
    """What to tell someone whose Phoenix will not render."""
    return (
        "The spans are in Phoenix — the API serves them — but its HTML routes are\n"
        "failing. arize-phoenix 11.38.0 calls Starlette's\n"
        "Jinja2Templates.TemplateResponse() with the pre-0.29 signature, and a\n"
        "newer Starlette requires the `name` argument, so every page 500s with\n"
        "TypeError. Check the server log. Downgrading Starlette to match would\n"
        "pull FastAPI back with it, and the web UI is a deliverable, so this is\n"
        "recorded as a known limitation rather than worked around."
    )


if __name__ == "__main__":
    raise SystemExit(main())
