#!/usr/bin/env python
"""Run instrumented assessments and export the spans.

    python scripts/export_traces.py

Runs a representative set of applications from **both** lending products through
the full graph with tracing on, then exports the spans to
``traces/phoenix_spans.jsonl``.

Two collection paths, tried in order:

1. **From a running Phoenix instance.** If a local Phoenix server is up, its
   span store is queried after the run and the real OTLP-exported spans are
   written out — the richer artifact, and the one whose ``run_id``/``span_id``
   the failure analysis cites.
2. **From an in-process span recorder.** With no collector running, a local
   exporter captures the same spans directly. Identical structure, same span
   names and attributes; it just never leaves the process.

Either way the export is machine-generated by committed code, carries latencies,
and covers multiple agents and every tool call.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

TRACES_DIR = REPO_ROOT / "traces"
SPANS_PATH = TRACES_DIR / "phoenix_spans.jsonl"
SUMMARY_PATH = TRACES_DIR / "trace_summary.json"

#: Applications covering both products and the cases worth having traced: the
#: temporal boundary, an adversarial packet, and each education product family.
DEFAULT_APPLICATIONS = (
    "synthetic_data/mortgage/applications/APP-000055.json",
    "synthetic_data/mortgage/applications/APP-000056.json",
    "synthetic_data/mortgage/applications/APP-000057.json",
    "synthetic_data/mortgage/applications/APP-000065.json",
    "synthetic_data/education/applications/APP-2026-00001.json",
    "synthetic_data/education/applications/APP-2026-00002.json",
    "synthetic_data/education/applications/APP-2026-00037.json",
)


class SpanRecorder:
    """An in-process OTel span exporter that keeps spans as plain dictionaries."""

    def __init__(self) -> None:
        self.spans: list[dict[str, Any]] = []

    def export(self, spans) -> Any:  # noqa: ANN001 - OTel's SpanExportResult
        from opentelemetry.sdk.trace.export import SpanExportResult

        for span in spans:
            self.spans.append(_span_to_dict(span))
        return SpanExportResult.SUCCESS

    def shutdown(self) -> None:
        return None

    def force_flush(self, timeout_millis: int = 30_000) -> bool:
        return True


def _span_to_dict(span) -> dict[str, Any]:  # noqa: ANN001
    ctx = span.get_span_context()
    parent = span.parent
    start_ns, end_ns = span.start_time, span.end_time
    return {
        "name": span.name,
        "trace_id": f"{ctx.trace_id:032x}",
        "span_id": f"{ctx.span_id:016x}",
        "parent_span_id": f"{parent.span_id:016x}" if parent else None,
        "start_time": datetime.fromtimestamp(start_ns / 1e9, tz=timezone.utc).isoformat(),
        "end_time": datetime.fromtimestamp(end_ns / 1e9, tz=timezone.utc).isoformat()
        if end_ns
        else None,
        "latency_ms": round((end_ns - start_ns) / 1e6, 3) if end_ns else None,
        "status": span.status.status_code.name if span.status else "UNSET",
        "attributes": {k: v for k, v in (span.attributes or {}).items()},
    }


def install_recorder(project_name: str) -> SpanRecorder:
    """Wire a recorder into the global tracer provider."""
    from opentelemetry import trace
    from opentelemetry.sdk.resources import Resource
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import SimpleSpanProcessor

    recorder = SpanRecorder()
    provider = TracerProvider(resource=Resource.create({"service.name": project_name}))
    provider.add_span_processor(SimpleSpanProcessor(recorder))
    trace.set_tracer_provider(provider)

    from src.observability import tracing

    tracing._TRACER = provider.get_tracer("credpilot.rag")  # noqa: SLF001
    tracing._TRACER_PROVIDER = provider  # noqa: SLF001
    tracing._INITIALIZED = True  # noqa: SLF001
    return recorder


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--applications", nargs="*", default=list(DEFAULT_APPLICATIONS))
    parser.add_argument("--phoenix", action="store_true",
                        help="export from a running Phoenix instance instead")
    parser.add_argument("--output", default=str(SPANS_PATH))
    args = parser.parse_args(argv)

    from src.console import use_utf8_stdio

    use_utf8_stdio()
    os.environ["CREDPILOT_TRACING"] = "1"

    if args.phoenix:
        from src.observability.tracing import configure_tracing

        configure_tracing(force=True)
        recorder = None
        print("Tracing via Phoenix OTLP exporter")
    else:
        recorder = install_recorder("credpilot")
        print("Tracing via in-process span recorder")

    print(f"Applications: {len(args.applications)}")
    print()

    from src.graph import build_graph, initial_state, state_evidence

    graph, context = build_graph()
    run_id = uuid.uuid4().hex
    runs = []
    try:
        for relative in args.applications:
            path = REPO_ROOT / relative
            state = initial_state(path)
            thread_id = f"trace-{state['application_id']}-{run_id[:8]}"
            result = graph.invoke(state, config={"configurable": {"thread_id": thread_id}})
            evidence = state_evidence(result)
            runs.append(
                {
                    "application_id": result.get("application_id"),
                    "loan_domain": result.get("loan_domain"),
                    "as_of_date": result.get("as_of_date"),
                    "thread_id": thread_id,
                    "nodes": result.get("steps"),
                    "evidence_count": len(evidence),
                    "recommendation": (result.get("recommendation") or {}).get("outcome"),
                    "requires_human_review": result.get("requires_human_review"),
                }
            )
            print(
                f"  {result.get('application_id'):<16} {result.get('loan_domain'):<15} "
                f"{len(evidence):>3} evidence  "
                f"{(result.get('recommendation') or {}).get('outcome')}"
            )
    finally:
        if context is not None:
            context.__exit__(None, None, None)

    from src.observability.tracing import flush_traces

    flush_traces()

    spans = recorder.spans if recorder else _fetch_from_phoenix()
    if not spans:
        print()
        print("No spans collected. Nothing written.")
        return 1

    TRACES_DIR.mkdir(parents=True, exist_ok=True)
    output = Path(args.output)
    with output.open("w", encoding="utf-8") as fh:
        for span in spans:
            fh.write(json.dumps(span, sort_keys=True, default=str) + "\n")

    summary = _summarize(spans, runs, run_id)
    SUMMARY_PATH.write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    print()
    print(f"Spans            {len(spans)}")
    print(f"Traces           {summary['trace_count']}")
    print(f"Distinct names   {len(summary['span_names'])}")
    for name, stats in sorted(summary["span_names"].items()):
        print(f"  {name:<22} {stats['count']:>4}  p50 {stats['p50_ms']:>8.2f} ms  "
              f"p95 {stats['p95_ms']:>8.2f} ms")
    print()
    print(f"Export  → {output.relative_to(REPO_ROOT)}")
    print(f"Summary → {SUMMARY_PATH.relative_to(REPO_ROOT)}")
    return 0


def _fetch_from_phoenix() -> list[dict[str, Any]]:
    try:
        import phoenix as px

        client = px.Client()
        frame = client.get_spans_dataframe(project_name="credpilot")
        return json.loads(frame.to_json(orient="records"))
    except Exception as exc:  # noqa: BLE001
        print(f"  could not read spans from Phoenix: {exc}")
        return []


def _percentile(values: list[float], pct: float) -> float:
    """Nearest-rank percentile.

    Duplicated from ``eval/retrieval/metrics.py`` rather than imported: runtime
    code must not depend on the evaluation package, which is the only code
    allowed to read the golden sets. Six lines is a better price than that
    dependency.
    """
    if not values:
        return 0.0
    ordered = sorted(values)
    rank = max(1, math.ceil(pct / 100.0 * len(ordered)))
    return float(ordered[min(rank, len(ordered)) - 1])


def _summarize(spans: list[dict], runs: list[dict], run_id: str) -> dict[str, Any]:
    by_name: dict[str, list[float]] = {}
    for span in spans:
        latency = span.get("latency_ms")
        if latency is not None:
            by_name.setdefault(span["name"], []).append(float(latency))

    return {
        "run_id": run_id,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "span_count": len(spans),
        "trace_count": len({s.get("trace_id") for s in spans if s.get("trace_id")}),
        "runs": runs,
        "span_names": {
            name: {
                "count": len(values),
                "p50_ms": round(_percentile(values, 50), 3),
                "p95_ms": round(_percentile(values, 95), 3),
                "total_ms": round(sum(values), 3),
            }
            for name, values in sorted(by_name.items())
        },
    }


if __name__ == "__main__":
    raise SystemExit(main())
